[[main]]
  name = "主页"
  url = "#about"
  weight = 10


[[main]]
  name = "实习经历"
  url = "#experience"
  weight = 30

[[main]]
  name = "比赛经历"
  url = "#accomplishments"
  weight = 40
  
[[main]]
  name = "科研经历"
  url = "#paper"
  weight = 20
  
[[main]]
  name = "联系方式"
  url = "#contact"
  weight = 60
